### ISSUE TITLE
Print dev server url

### ISSUE THREAD

**Issue by simon-bourne** [rustminded/xtask-wasm#47]
When the dev server has finished building and is ready to accept connections, it would be great if it printed the URL. Some terminals will spot URLs and allow you to click on them, so the printing the full URL would be useful. e.g. `http://127.0.0.1:8000/`. Also, it would be useful to print the URL again after a rebuild, so there's always something to click on at the bottom of the screen.

Thanks!

**Comment by yozhgoor** [comment]
Hey, thank you for the issue.

We use the [`log`](https://docs.rs/log/latest/log/) crate, like here using `cargo xtask start` with the example in [examples/demo](https://github.com/rustminded/xtask-wasm/tree/main/examples/demo) that use [`env_logger`](https://docs.rs/env_logger/latest/env_logger/):

```console
[2022-02-24T17:11:38Z INFO  xtask] Starting the development server...
[2022-02-24T17:11:39Z INFO  xtask_wasm::dev_server] Development server running at: http://127.0.0.1:8000
[2022-02-24T17:11:39Z INFO  xtask] Generating package...
```
You can also use directly the `ip` and `port` fields from the `DevServer` in a `format!` so you can use another lib or way to display it as you like.

The reason we do not display the address after re-running the command is because we do not restart the DevServer. As long as the command is executed, the IP address will not change. It's little to print it every time, but is it really worth it?

What do you think about this @cecton?

**Comment by cecton** [comment]
I think I told ya we need to reprint the url right after the build

**Comment by cecton** [comment]
But I think I also said it wasn't easy for some reason :sweat_smile:

**Comment by yozhgoor** [comment]
i think you told me that one time is good enough at the start

**Comment by cecton** [comment]
you wanna fight? :fist_oncoming:

**Comment by yozhgoor** [comment]
always.

**Comment by cecton** [comment]
I guess in order to do this you will need to add a field in `Watch` that will run a closure when a command succeeds.

But then in xtask-watch you need somehow to wait for the process to finish (and succeed) before running that closure.

So I guess you will need to spawn a thread to be able to wait on the subprocess :thinking: I don't see any easier solution than that.

**Comment by cecton** [comment]
Maybe have a look at how they did it in cargo-watch? They might have an easier solution

**Comment by cecton** [comment]
> What do you think about this @cecton?

(I totally agree with @simon-bourne btw)

**Comment by simon-bourne** [comment]
Thanks. I'd missed the log message, then foolishly disabled logging to keep my code minimal (it was for an example, so I didn't want anything unnecessary).

Regarding how to implement printing the URL after each change: I did wonder if it would be nicer for the dev server (and `xtask-watch`?) to run a closure each time there were changes, rather than run a command. It's more versatile, more obvious what client code is doing at a  glance, and more type safe. Crates like `xshell` and `duct` make it trivial to run a command when that's what you really need.

**Comment by cecton** [comment]
> run a closure each time there were changes, rather than run a command

Closures are not cancellable. With the command you can make multiple changes in a short span of time and it will kill the previous process to keep only the latest.

[`wasm-run`](https://github.com/IMI-eRnD-Be/wasm-run) used a closure and the user experience was terrible beyond imagination. Especially in big apps that are slow to compile.

> It's more versatile, more obvious what client code is doing at a glance

If you have ideas on how to make what the client code is doing more obvious don't hesitate to share. We made a lot of efforts to make it very easy already but new point of views can improve things.

**Comment by simon-bourne** [comment]
That makes sense and kind of blows that idea out of the water! Anyway, it's been great to use so far.
